apiVersion: apps/v1
kind: Deployment
metadata:
  name: support-ticket-portal-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: peterith/support-ticket-portal-client:latest
          ports:
            - containerPort: 80
